Cubic splines overhaul
JohnTheCoolingFan/bevy pull request #2
Opened 2024-02-01 21:03 UTC by NthTensor

+ Re-touched a bunch of the other spline docs so they all agree and use the same style. I don't think Alice will mind doing this here, as she was asking for docs on some stuff already not touched by this PR (like the characteristic matrix of a normal BSpline).
+ I replaced all "Knot Vector" and "Weight Vector" language with "knots" and "weights". Less verbose.
+ Knots are now normalized such that the intervals between knots form an exact cover of `[0, N]` where `N` is the number of curves. This makes both nurbs and b-splines have the same parametric domain.
+ `RationalSegement` now tracks the size of it's parametric domain, as derived from the knot vector.
+ `RationalCurve` now allows for different sizes of segment, and clamps the parameter to the curve domain. The output of `RationalCurve::segment` is mapped to `[0, 1]`.
+ Added detailed references to the papers where possible.

2024-02-02 09:04 UTC, JohnTheCoolingFan requested changes
Very good improvement, although there are some nitpicks and typos I've highlighted. Would like to know what you think about these so they can be resolved and it'll be ready to be merged to the main PR!

2024-02-02 09:04 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +/// Tangents are automatically computed based on the position of control points.
```suggestion
/// Tangents are automatically computed based on the positions of control points.
```
I think this would be better

2024-02-02 09:04 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +        /// Expected number of knots
```suggestion
    #[error("Wrong number of knots: expected {expected}, provided {provided}")]
    KnotsNumberMismatch {
        /// Expected number of knots
```
I think this variant name should be more clear that the thing that mismatches is the number of knots.

2024-02-02 09:04 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +        /// Expected number of weights
```suggestion
    #[error("Incorect number of weights: expected {expected}, provided {provided}")]
    WeightsNumberMismatch {
        /// Expected number of weights
```
Same here

2024-02-02 09:04 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +    #[error("Invalid knots: all knots are equal")]
```suggestion
    /// The provided knots were all equal. Knots must contain at least one increasing pair.
    #[error("Invalid knots: all knots are equal")]
```

2024-02-02 09:04 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +/// and can create sharp corners.
```suggestion
/// ### Non-uniformity
/// The 'NU' part of NURBS stands for "Non-Uniform". This has to do with a parameter called 'knots'.
/// The knots are a non-decreasing sequence of floating point numbers. The first and last three pairs of
/// knots control the behavior of the curve as it approaches it's endpoints. The intermediate pairs
/// each control the length of one segment of the curve. Multiple repeated knot values are called
/// "knot multiplicity". Knot multiplicity in the intermediate knots causes a "zero-length" segments,
/// and can create sharp corners.
```

2024-02-02 09:04 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +/// be assigned a weighting, which controls how much it effects the curve recitative to the other points.
```suggestion
/// ### Rationality
/// The 'R' part of NURBS stands for "Rational". This has to do with NURBS allowing each control point to
/// be assigned a weighting, which controls how much it effects the curve compared to the other points.
```

"Recitative" is a quite obscure word, so I think replacing it with something more common would make the documentation clearer for more people.

2024-02-02 09:04 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +/// C0, meaning it has no jumps or holes.
```suggestion
/// When there is no knot multiplicity, the curve is C2 continuous, meaning it has no holes or jumps and the
/// tangent vector changes smoothly along the entire curve length. Like the [`CubicBSpline`], the acceleration
/// continuity makes it useful for camera paths. Knot multiplicity of 2 in intermediate knots reduces the
/// continuity to C2, and Knot multiplicity of 3 reduces the continuity to C0. The curve is always at least
/// C0, meaning it has no jumps or holes.
```

2024-02-02 09:04 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +        let max = knots.last().unwrap().clone();
```suggestion
        let min = *knots.first().unwrap();
        let max = *knots.last().unwrap();
```
No need for explicit clone I think

2024-02-02 09:04 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +    /// difference of 1. "Multiplicity" means that there are N consecutive elements that have the same value.
```suggestion
    /// The start and end knots have multiplicity 4, and intermediate knots have multiplicity 0 and
    /// difference of 1.
```
As you have explained what Multiplicity is in the main doc comment of `CubicNurbs`, I don't think there is need to have this here.

2024-02-02 09:04 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +        // + The second term should uses R when it should use the first derivative.
```suggestion
        // A derivation for the following equations can be found in "Matrix representation for NURBS
        // curves and surfaces" by Choi et al. See equation 20. Note: In come copies of this paper, equation 20
        // is printed with the following two errors:
        // + The first term has incorrect sign.
        // + The second term uses R when it should use the first derivative.
```
Typo

2024-02-02 09:04 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +/// `N` is at-least the number of segments.
```suggestion
/// A collection of [`RationalSegment`]s chained into a single parametric curve. Has domain `[0, N)` where
/// `N` is the number of segments.
```

2024-02-02 09:04 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +    }
Why not expose this method? I think it might be useful. Correct me if I'm wrong.
```suggestion
    /// Returns the length of of the domain of the parametric curve.
    #[inline]
    pub fn domain(&self) -> f32 {
        self.segments.iter().map(|segment| segment.knot_span).sum()
    }
```

2024-02-02 09:04 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +        const EPSILON: f32 = 0.1;
This constant seems to be too big. Can it be reduced to something smaller? As it is, I think the allowed error would be very noticeable at such scale.

2024-02-02 09:04 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +        /// Expected number of knots
This change would also require to change the usage

2024-02-02 10:53 UTC, NthTensor commented on crates/bevy_math/src/cubic_splines.rs
> +    }
Yep, good catch!

2024-02-02 11:07 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +                    t = t - segment.knot_span
This line causes CI to error.
```suggestion
                    t -= segment.knot_span;
```

2024-02-02 11:08 UTC, JohnTheCoolingFan commented
Marked another place where CI errors

2024-02-02 20:17 UTC, NthTensor commented on crates/bevy_math/src/cubic_splines.rs
> +/// `N` is at-least the number of segments.
So the domain of the rational curve is implicit. I'm just going to remove this entire line, it's too complicated to explain and it's clamped anyway.

2024-02-03 04:21 UTC, NthTensor commented
Made those fixes and finally got the circular arc test right. Ready for merge and final reviews?

2024-02-03 12:01 UTC, JohnTheCoolingFan approved these changes

2024-02-03 12:05 UTC, JohnTheCoolingFan approved these changes

2024-02-03 12:05 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +                }
```suggestion
                if t < segment.knot_span {
                    // The division here makes t a normalized parameter in [0, 1] that can be properly
                    // evaluated against a cubic curve segment. See equations 6 & 16 from "Matrix representation
                    // of NURBS curves and surfaces" by Choi et al. or equation 3 from "General Matrix
                    // Representations for B-Splines" by Qin.
                    return (segment, t / segment.knot_span);
                }
                t -= segment.knot_span;
```
CI errors on this

2024-02-03 12:13 UTC, JohnTheCoolingFan requested changes

2024-02-03 12:13 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +    /// should produce pretty much the same output.
CI again
```suggestion
    /// Test that [`RationalCurve`] properly generalizes [`CubicCurve`]. A Cubic upgraded to a rational
    /// should produce pretty much the same output.
```

2024-02-03 12:13 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +            )
```suggestion
            assert!(
                f32::abs(point.length() - 1.0) < EPSILON,
                "Point {i} is not on the unit circle: {point:?} has length {}",
                point.length()
            );
```

2024-02-03 12:17 UTC, JohnTheCoolingFan approved these changes

2024-02-03 12:25 UTC, JohnTheCoolingFan requested changes

2024-02-03 12:25 UTC, JohnTheCoolingFan commented on crates/bevy_math/src/cubic_splines.rs
> +/// [`CubicNURBS`], or convert [`CubicCurve`] using `into/from`.
Wrong type name in doc
```suggestion
/// [`CubicNurbs`], or convert [`CubicCurve`] using `into/from`.
```

2024-02-03 12:39 UTC, JohnTheCoolingFan approved these changes

2024-02-03 12:40 UTC, merged